todo/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('todo/', include('todos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todos/urls.py
from django.urls import path
from . import views

app_name = 'task'

urlpatterns = [
    path('add_task/', views.add_task, name='addTask'),
    path('mark_as_done/<int:pk>/', views.mark_as_done, name='mark_as_done'),
    path("mark_as_undone/<int:pk>/", views.mark_as_undone, name='mark_as_undone'),
    path('edit_task/<int:pk>/', views.edit_task, name='edit_task'),
    path('delete_task/<int:pk>/', views.delete_task, name='delete_task'),
]

todos/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task = models.CharField(max_length=255, unique=True)
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.task

todo/views.py
from django.http import HttpResponse
from django.shortcuts import render
from todos.models import Task



def home(request):
    # return HttpResponse("home page")
    uncomplete_tasks = Task.objects.filter(is_completed=False).order_by('-updated_at')
    completed_task = Task.objects.filter(is_completed=True)
    print(f"\nCompleted task - {completed_task}")
    context = {
        'tasks': uncomplete_tasks,
        'ctasks': completed_task
    }
    # print("Uncomplete Tasks - ",uncomplete_tasks)
    return render(request,'home.html', context)

todos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from todos.models import Task
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.db import transaction

# Create your views here.

@require_POST
def add_task(request):
    task = request.POST.get('task','').strip()
    if not task:
        print("Task is empty!")
        return redirect('home')
    
    try:
        with transaction.atomic():
            Task.objects.create(task=task)
            print("New Task created successfully!")
    except Exception as e:
        print(f"Err occured while adding task in db - {str(e)}")
    
    return redirect('home')
    
    # result = Task.objects.create(task=task)
    # print(f"result - {result}")
    # return render(request, 'home.html')
    # return redirect('home')


def mark_as_done(reqeust, pk):
    try:
        with transaction.atomic():
            got_task = get_object_or_404(Task, pk=pk)
            got_task.is_completed = True
            got_task.save()
    except Exception as e:
        print(f"Err occured while marking the task as done - {str(e)}")
    return redirect('home')


def mark_as_undone(request, pk):
    try:
        with transaction.atomic():
            got_task = get_object_or_404(Task, pk=pk)
            got_task.is_completed = False
            got_task.save()
        print("task is marked as undone")
    except Exception as e:
         print(f"Err occured while marking the task as done - {str(e)}")
    return redirect('home')


def edit_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        new_task = request.POST['task']
        task.task = new_task
        task.save()
        return redirect('home')
    else:
        context= {
            'task': task
        }
    return render(request, 'edit_task.html',context)

def delete_task(reqeust, pk):
    try:
        with transaction.atomic():
            task = get_object_or_404(Task,pk=pk)
            task.delete()
            return redirect('home')
    except Exception as e:
        print(f"Err occurred while deleting the task - {str(e)}")
        return redirect('home')

templates/edit_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Task</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
</head>
<body>
    <div class="container">
        <h3 class="pt-5 pb-5 text-center">Django TODO App - Edit Task</h3>
        <form action="{% url 'task:edit_task' task.id %}" method="POST" style="width: 500px; margin: auto;">
            {% csrf_token %}
            <div class="form-group">
                <div class="d-flex gap-2">
                <input type="text" name="task" class="form-control" placeholder="Update task" value="{{ task.task }}" required>
                <button type="submit" class="btn btn-primary" style="width: 200px;"> <i class="fa fa-plus"></i> Update</button>
                </div>
            </div>
        </form>
    </div>
    
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO LIST - Home</title>
    <link rel="icon" type="image/x-icon" href="/static/to-do-list.mp4">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <style>
        .form-control{
        padding: 1.375rem .75rem !important;
    }
    </style>
</head>
<body>
    <div class="container">
        <h3 class="pt-5 text-center">Django ToDo App</h3>
        <div class="row">
            <h4>My Day</h4>
            <p class="text-muted">{% now "jS F Y" %}</p>
            <div class="col-md-7 col-lg-7" style="height: 450px; overflow: scroll;">
                <!-- List of all the tasks for the day -->
                {% for task in tasks %}
                <div class="card m-1">
                    <div class="card-body">
                        {{ task.task }}
                        <span style="position: relative; float: right;">
                            <a href="{% url 'task:mark_as_done' task.pk %}" class="btn btn-success"><i class="fa fa-check"></i> Mark as Done</a>
                            <a href="{% url 'task:delete_task' task.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                            <a href="{% url 'task:edit_task' task.id %}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                        </span>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-5 col-lg-5">
                <h5>Completed Tasks</h5>
                <!-- List of all the tasks that have completed -->
                {% for task in ctasks %}
                <div class="card m-1">
                    <div class="card-body">
                        {{ task.task }}
                        <span style="position: relative; float: right;">
                            <a href="{% url 'task:mark_as_undone' task.pk %}" class="btn btn-danger"><i class="fa fa-times"></i> Mark as Undone</a>
                        </span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <!-- ADD TASK FORM -->
            <div class="row mt-4">
                <div class="col-md-7">
                    <form action="{% url 'task:addTask' %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text"
                                name="task"
                                class="form-control"
                                placeholder="Add a task"
                                required>
                            <button type="submit" class="btn btn-primary px-4">
                                <i class="fa fa-plus"></i> Add
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>